name: build

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:

    - name: show Env
      run: |
         sudo uname -a
         
    - name: set apt source list
      run: |
         sudo cat /etc/apt/sources.list && sudo apt-get upgrade
         
    - name: Install Dependencies
      run: sudo -E apt-get -qq update && sudo -E apt-get -qq install -y git-core gnupg flex bison build-essential zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 libncurses5 lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z1-dev libgl1-mesa-dev libxml2-utils xsltproc unzip fontconfig && echo "install utils" && sudo -E apt-get -qq install -y sudo rsync && echo "install packages for build mesa3d or meson related" && sudo -E apt-get -qq install -y python3-pip pkg-config python3-dev ninja-build && sudo pip3 install mako meson && echo "packages for legacy mesa3d (< 22.0.0)"  && sudo -E apt-get -qq install -y python-mako python-enum34 gettext
