name: build

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Install Dependencies
      run: apt-get install -y git-core gnupg flex bison build-essential zip curl zlib1g-dev \
        gcc-multilib g++-multilib libc6-dev-i386 libncurses5 lib32ncurses5-dev x11proto-core-dev \
        libx11-dev lib32z1-dev libgl1-mesa-dev libxml2-utils xsltproc unzip fontconfig \
        && echo "install utils" \
        && apt-get install -y sudo rsync \
        && echo "install packages for build mesa3d or meson related" \
        && apt-get install -y python3-pip pkg-config python3-dev ninja-build \
        && pip3 install mako meson \
        && echo "packages for legacy mesa3d (< 22.0.0)" \
        && apt-get install -y python2 python-mako python-is-python2 python-enum34 gettext
