name: build

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    
    - name: set apt source list
      run: |
        sudo cat /etc/apt/sources.list && sudo -E apt-get -qq update
         
    - name: Install Dependencies
      run: |
        sudo -E apt-get -qq install -y git-core gnupg flex bison build-essential zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 libncurses5 lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z1-dev libgl1-mesa-dev libxml2-utils xsltproc unzip fontconfig && echo "install utils" && sudo -E apt-get -qq install -y sudo rsync && echo "install packages for build mesa3d or meson related" && sudo -E apt-get -qq install -y python3-pip pkg-config python3-dev ninja-build && sudo pip3 install mako meson && echo "packages for legacy mesa3d (< 22.0.0)"  && sudo -E apt-get -qq install -y python-mako python-enum34 gettext
      
    - name: set Env
      run: |
        HOME=/home/$username && USER=$username && PATH=/src/.repo/repo:/src/prebuilts/jdk/jdk8/linux-x86/bin/:$PATH && where java
         
